CREATE TABLE topicos (
  id BIGINT NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(200) NOT NULL,
  mensaje TEXT NOT NULL,
  fecha_creacion DATETIME NOT NULL,
  status VARCHAR(30) NOT NULL,
  autor VARCHAR(120) NOT NULL,
  curso VARCHAR(120) NOT NULL,
  PRIMARY KEY (id)
);